# Generated by Django 5.1 on 2024-11-25 05:57

import django.db.models.deletion
import django_extensions.db.fields
import music.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("music", "0001_initial"),
        ("music", "0002_alter_album_artist_alter_artist_user"),
        ("music", "0003_alter_album_release_date"),
        ("music", "0004_album_slug"),
        ("music", "0005_artist_following"),
        ("music", "0006_albumpopularity_trackpopularity"),
        ("music", "0007_alter_albumpopularity_artist_and_more"),
        ("music", "0008_alter_albumpopularity_options_and_more"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Stage Name"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ManyToManyField(
                        related_name="followers", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "artist",
                "verbose_name_plural": "artists",
            },
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("release_date", models.DateTimeField(verbose_name="Release Date")),
                (
                    "cover_art",
                    models.ImageField(
                        upload_to=music.models._album_cover_upload_to,
                        verbose_name="Cover Art",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="music.artist",
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from="name",
                        verbose_name="slug",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from="title",
                        verbose_name="slug",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for an immediate activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                ("file", models.FileField(upload_to=music.models._tracks_upload_to)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("pop", "Pop"),
                            ("rock", "Rock"),
                            ("hip_hop", "Hip Hop"),
                            ("electronic", "Electronic"),
                            ("jazz", "Jazz"),
                            ("classical", "Classical"),
                            ("country", "Country"),
                            ("r_n_b", "R&B"),
                            ("reggae", "Reggae"),
                            ("folk", "Folk"),
                            ("blues", "Blues"),
                            ("metal", "Metal"),
                            ("punk", "Punk"),
                            ("alternative", "Alternative"),
                            ("indie", "Indie"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=100,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="music.album",
                    ),
                ),
                (
                    "artists",
                    models.ManyToManyField(related_name="tracks", to="music.artist"),
                ),
            ],
            options={
                "verbose_name": "track",
                "verbose_name_plural": "tracks",
            },
        ),
        migrations.CreateModel(
            name="AlbumPopularity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "artist",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="popularity",
                        to="music.artist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Popularity Score",
                "verbose_name_plural": "Popularities Score",
            },
        ),
        migrations.CreateModel(
            name="TrackPopularity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "track",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="popularity",
                        to="music.track",
                    ),
                ),
            ],
            options={
                "verbose_name": "Popularity Score",
                "verbose_name_plural": "Popularities Score",
            },
        ),
    ]
