# Generated by Django 5.1 on 2024-11-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0002_alter_album_artist_alter_artist_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="release_date",
            field=models.DateTimeField(verbose_name="Release Date"),
        ),
    ]
