# Generated by Django 5.1 on 2024-11-20 09:25

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0003_alter_album_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name", verbose_name="slug"
            ),
        ),
    ]
