# Generated by Django 5.1 on 2024-11-22 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0005_artist_following"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlbumPopularity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "artist",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="music.artist"
                    ),
                ),
            ],
            options={
                "verbose_name": "Popularity",
                "verbose_name_plural": "Popularities",
            },
        ),
        migrations.CreateModel(
            name="TrackPopularity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "track",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="music.track"
                    ),
                ),
            ],
            options={
                "verbose_name": "Popularity",
                "verbose_name_plural": "Popularities",
            },
        ),
    ]
