# Generated by Django 5.1.1 on 2024-11-18 12:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="otp",
            field=models.CharField(default=accounts.models._generate_otp, max_length=6),
        ),
    ]
