# Generated by Django 5.1 on 2024-11-19 04:59

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_otp_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.models._upload_to
            ),
        ),
    ]
