# Generated by Django 5.1 on 2024-11-19 10:10

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="account_type",
        ),
        migrations.AlterField(
            model_name="user",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
    ]
